import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        environment: 'jsdom',
        include: ['src/**/*.test.ts'],
        clearMocks: true,
        restoreMocks: true,
        coverage: {
            provider: 'v8',
            reporter: ['text', 'html'],
            reportsDirectory: './coverage',
            include: [
                'src/app-shell.ts',
                'src/app-state.ts',
                'src/musicbrainz.ts',
                'src/components/media-controls.ts',
                'src/components/sidebar.ts',
                'src/components/overlays/about-modal.ts',
                'src/components/overlays/error-modal.ts',
                'src/components/overlays/image-file-modal.ts',
                'src/components/overlays/index.ts',
                'src/components/overlays/musicbrainz-entity-modal.ts',
                'src/components/overlays/play-order-menu.ts',
                'src/components/overlays/playlist-menu.ts',
                'src/components/overlays/playlist-modal.ts',
                'src/components/overlays/playlist-target-modal.ts',
                'src/components/overlays/queue-confirm-modal.ts',
                'src/components/overlays/settings-modal.ts',
                'src/components/overlays/share-modal.ts',
                'src/components/overlays/sidebar-queue-menu.ts',
                'src/components/overlays/technical-info-modal.ts',
                'src/components/overlays/text-file-modal.ts',
                'src/components/overlays/track-meta-menu.ts',
                'src/constants/ui-timings.ts',
                'src/services/library-data-service.ts',
                'src/utils/display-helpers.ts',
                'src/utils/lastfm-request-scheduler.ts',
                'src/utils/musicbrainz-entity-helpers.ts',
                'src/utils/musicbrainz-request-scheduler.ts',
                'src/utils/settings-normalization.ts',
                'src/utils/shortcut-bindings.ts',
            ],
            exclude: [
                'src/**/*.d.ts',
                'src/**/*.test.ts',
                'src/main.ts',
                'wailsjs/**',
            ],
        },
    },
});