// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AudioGetState():Promise<main.AudioPlaybackState>;

export function AudioListOutputDevices():Promise<Array<main.AudioOutputDevice>>;

export function AudioLoadTrack(arg1:string):Promise<main.AudioPlaybackState>;

export function AudioLoadTrackWithReplayGainContext(arg1:string,arg2:Array<string>):Promise<main.AudioPlaybackState>;

export function AudioPause():Promise<main.AudioPlaybackState>;

export function AudioPlay():Promise<main.AudioPlaybackState>;

export function AudioQueueNextTrack(arg1:string,arg2:string):Promise<main.AudioPlaybackState>;

export function AudioQueueNextTrackWithReplayGainContext(arg1:string,arg2:string,arg3:Array<string>):Promise<main.AudioPlaybackState>;

export function AudioReinitializeBackend():Promise<main.AudioPlaybackState>;

export function AudioSeek(arg1:number):Promise<main.AudioPlaybackState>;

export function AudioSetVolume(arg1:number):Promise<main.AudioPlaybackState>;

export function AudioStop():Promise<main.AudioPlaybackState>;

export function GetAppVersion():Promise<string>;

export function GetLibraryFolderCoverPath(arg1:string):Promise<string>;

export function GetLibraryFolderPage(arg1:string,arg2:number,arg3:number):Promise<main.LibraryFolderPage>;

export function GetLibraryFolderTrackCount(arg1:string):Promise<number>;

export function GetLibraryFolderTrackPaths(arg1:string):Promise<Array<string>>;

export function GetLibraryIndexedFilePage(arg1:string,arg2:number,arg3:number):Promise<main.LibraryIndexedFilePage>;

export function GetListenBrainzRecordingFeedback(arg1:string):Promise<number>;

export function GetSettings():Promise<main.AppSettings>;

export function InitializeAudioBackend():Promise<main.AudioPlaybackState>;

export function IsLibraryFolderImmediateDescendantsEnumerated(arg1:string):Promise<boolean>;

export function LoadPlaylistFile(arg1:string):Promise<main.PlaylistLoadResult>;

export function LogFrontendMessage(arg1:string):Promise<void>;

export function LookupArtistByMBID(arg1:string):Promise<main.MusicBrainzArtistInfo>;

export function LookupMusicBrainzEntity(arg1:string,arg2:string):Promise<main.MusicBrainzEntityInfo>;

export function LookupMusicBrainzExploration(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:string):Promise<main.MusicBrainzExplorationGraph>;

export function LookupTrackMusicBrainzMetadata(arg1:string,arg2:string):Promise<main.MusicBrainzTrackMetadata>;

export function OpenFolderInFileBrowser(arg1:string):Promise<boolean>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReadImageThumbnail(arg1:string,arg2:number):Promise<main.EmbeddedCoverArt>;

export function ReadTextFile(arg1:string):Promise<string>;

export function ReadTrackEmbeddedCover(arg1:string):Promise<main.EmbeddedCoverArt>;

export function ReadTrackTags(arg1:Array<string>):Promise<Record<string, main.TrackTags>>;

export function ReadTrackTagsFromBlobs(arg1:Array<main.TrackBlob>):Promise<Record<string, main.TrackTags>>;

export function ResolveLibraryFolderForPath(arg1:string):Promise<string>;

export function SavePlaylistFile(arg1:string,arg2:Array<string>):Promise<boolean>;

export function SaveSettings(arg1:main.AppSettings):Promise<main.AppSettings>;

export function ScanConfiguredLibraryFolders():Promise<main.LibraryScanResult>;

export function ScanLibraryFolder(arg1:string):Promise<main.LibraryScanResult>;

export function SearchLibrary(arg1:string,arg2:number,arg3:number):Promise<main.LibrarySearchPage>;

export function SelectLibraryFolder():Promise<string>;

export function SelectPlaylistFile():Promise<string>;

export function SelectPlaylistSaveFile():Promise<string>;

export function ShowErrorDialog(arg1:string,arg2:string):Promise<void>;

export function SubmitListenBrainz(arg1:string,arg2:main.ListenBrainzTrackMetadata,arg3:number):Promise<void>;

export function SubmitListenBrainzRecordingFeedback(arg1:string,arg2:number):Promise<void>;
