// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AudioGetState():Promise<main.AudioPlaybackState>;

export function AudioLoadTrack(arg1:string):Promise<main.AudioPlaybackState>;

export function AudioPause():Promise<main.AudioPlaybackState>;

export function AudioPlay():Promise<main.AudioPlaybackState>;

export function AudioSeek(arg1:number):Promise<main.AudioPlaybackState>;

export function AudioSetVolume(arg1:number):Promise<main.AudioPlaybackState>;

export function AudioStop():Promise<main.AudioPlaybackState>;

export function GetSettings():Promise<main.AppSettings>;

export function InitializeAudioBackend():Promise<main.AudioPlaybackState>;

export function LoadPlaylistFile(arg1:string):Promise<main.PlaylistLoadResult>;

export function LookupArtistByMBID(arg1:string):Promise<main.MusicBrainzArtistInfo>;

export function LookupMusicBrainzEntity(arg1:string,arg2:string):Promise<main.MusicBrainzEntityInfo>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function ReadTrackTags(arg1:Array<string>):Promise<Record<string, main.TrackTags>>;

export function ReadTrackTagsFromBlobs(arg1:Array<main.TrackBlob>):Promise<Record<string, main.TrackTags>>;

export function SaveSettings(arg1:main.AppSettings):Promise<main.AppSettings>;

export function ScanLibraryFolder(arg1:string):Promise<main.LibraryScanResult>;

export function SelectLibraryFolder():Promise<string>;

export function SelectPlaylistFile():Promise<string>;

export function SubmitListenBrainz(arg1:string,arg2:main.ListenBrainzTrackMetadata,arg3:number):Promise<void>;
