// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LookupArtistByMBID(arg1) {
  return window['go']['main']['App']['LookupArtistByMBID'](arg1);
}

export function ReadTrackTags(arg1) {
  return window['go']['main']['App']['ReadTrackTags'](arg1);
}

export function ReadTrackTagsFromBlobs(arg1) {
  return window['go']['main']['App']['ReadTrackTagsFromBlobs'](arg1);
}
