// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AudioGetState() {
  return window['go']['main']['App']['AudioGetState']();
}

export function AudioLoadTrack(arg1) {
  return window['go']['main']['App']['AudioLoadTrack'](arg1);
}

export function AudioPause() {
  return window['go']['main']['App']['AudioPause']();
}

export function AudioPlay() {
  return window['go']['main']['App']['AudioPlay']();
}

export function AudioSeek(arg1) {
  return window['go']['main']['App']['AudioSeek'](arg1);
}

export function AudioSetVolume(arg1) {
  return window['go']['main']['App']['AudioSetVolume'](arg1);
}

export function AudioStop() {
  return window['go']['main']['App']['AudioStop']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetLibraryFolderCoverPath(arg1) {
  return window['go']['main']['App']['GetLibraryFolderCoverPath'](arg1);
}

export function GetLibraryFolderPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLibraryFolderPage'](arg1, arg2, arg3);
}

export function GetLibraryFolderTrackPaths(arg1) {
  return window['go']['main']['App']['GetLibraryFolderTrackPaths'](arg1);
}

export function GetLibraryIndexedFilePage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLibraryIndexedFilePage'](arg1, arg2, arg3);
}

export function GetListenBrainzRecordingFeedback(arg1) {
  return window['go']['main']['App']['GetListenBrainzRecordingFeedback'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InitializeAudioBackend() {
  return window['go']['main']['App']['InitializeAudioBackend']();
}

export function IsLibraryFolderImmediateDescendantsEnumerated(arg1) {
  return window['go']['main']['App']['IsLibraryFolderImmediateDescendantsEnumerated'](arg1);
}

export function LoadPlaylistFile(arg1) {
  return window['go']['main']['App']['LoadPlaylistFile'](arg1);
}

export function LogFrontendMessage(arg1) {
  return window['go']['main']['App']['LogFrontendMessage'](arg1);
}

export function LookupArtistByMBID(arg1) {
  return window['go']['main']['App']['LookupArtistByMBID'](arg1);
}

export function LookupMusicBrainzEntity(arg1, arg2) {
  return window['go']['main']['App']['LookupMusicBrainzEntity'](arg1, arg2);
}

export function LookupMusicBrainzExploration(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LookupMusicBrainzExploration'](arg1, arg2, arg3, arg4, arg5);
}

export function LookupTrackMusicBrainzMetadata(arg1, arg2) {
  return window['go']['main']['App']['LookupTrackMusicBrainzMetadata'](arg1, arg2);
}

export function OpenFolderInFileBrowser(arg1) {
  return window['go']['main']['App']['OpenFolderInFileBrowser'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function ReadTrackTags(arg1) {
  return window['go']['main']['App']['ReadTrackTags'](arg1);
}

export function ReadTrackTagsFromBlobs(arg1) {
  return window['go']['main']['App']['ReadTrackTagsFromBlobs'](arg1);
}

export function SavePlaylistFile(arg1, arg2) {
  return window['go']['main']['App']['SavePlaylistFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanLibraryFolder(arg1) {
  return window['go']['main']['App']['ScanLibraryFolder'](arg1);
}

export function SearchLibrary(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchLibrary'](arg1, arg2, arg3);
}

export function SelectLibraryFolder() {
  return window['go']['main']['App']['SelectLibraryFolder']();
}

export function SelectPlaylistFile() {
  return window['go']['main']['App']['SelectPlaylistFile']();
}

export function SelectPlaylistSaveFile() {
  return window['go']['main']['App']['SelectPlaylistSaveFile']();
}

export function SubmitListenBrainz(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitListenBrainz'](arg1, arg2, arg3);
}

export function SubmitListenBrainzRecordingFeedback(arg1, arg2) {
  return window['go']['main']['App']['SubmitListenBrainzRecordingFeedback'](arg1, arg2);
}
